# Turns the WGSL sources into a C++ header of NUL terminated char arrays, so the
# library does not read shaders from the filesystem at run time (which a WASM build
# may not have). Byte arrays rather than raw string literals, since MSVC caps string
# literals at 16 KiB.
#
#   cmake -DOUTPUT=<header> -DINPUTS="a.wgsl;b.wgsl" -P embed_wgsl.cmake

set(content "// Generated by webgpu/cmake/embed_wgsl.cmake from webgpu/shaders/*.wgsl. Do not edit.\n#pragma once\n\n")

foreach (input ${INPUTS})
	get_filename_component(name ${input} NAME_WE)
	file(READ ${input} hex HEX)
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
	# Break the initializer into lines of 32 bytes.
	string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n\t" hex "${hex}")
	string(APPEND content "static const char wgsl_${name}[] = {\n\t${hex}0x00\n};\n\n")
endforeach()

if (EXISTS ${OUTPUT})
	file(READ ${OUTPUT} existing)
	if ("${existing}" STREQUAL "${content}")
		return()
	endif()
endif()
file(WRITE ${OUTPUT} "${content}")
